name: example
description: Demo project for Color picker field.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  color_picker_field:
    path: ../
  flutter_localizations: # Add this line
    sdk: flutter 
  flutter_lints: ^1.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

